/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_login1;

import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi1;
/**
 *
 * @author DELL
 */
public class formadd extends javax.swing.JFrame {

    /**
     * Creates new form formadd
     */
    public formadd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PASSWORDADD = new javax.swing.JLabel();
        USERNAMEADD = new javax.swing.JLabel();
        ISIANPASSWORDADD = new javax.swing.JTextField();
        ISIANUSERNAMEADD1 = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORM REGISTRASI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        PASSWORDADD.setText("PASSWORD : ");
        jPanel1.add(PASSWORDADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        USERNAMEADD.setText("USERNAME : ");
        jPanel1.add(USERNAMEADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        ISIANPASSWORDADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISIANPASSWORDADDActionPerformed(evt);
            }
        });
        jPanel1.add(ISIANPASSWORDADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, -1));
        jPanel1.add(ISIANUSERNAMEADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, -1));

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
   String username = ISIANUSERNAMEADD1.getText();
String password = ISIANPASSWORDADD.getText();

try{
Statement statement = (Statement) koneksi1.GetConnection().createStatement();
statement.executeUpdate("insert into tabellogin VALUES ('" + username +"','"+ password +"');");
statement.close ();
JOptionPane.showMessageDialog(null, "selamat data kamu berhasil disimpan");
       new formlogin1().show();
        this.dispose();
}catch (Exception t){
JOptionPane.showMessageDialog(null, "maaf! data kamu gagal disimpan");
}    
    }//GEN-LAST:event_ADDActionPerformed

    private void ISIANPASSWORDADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISIANPASSWORDADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISIANPASSWORDADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField ISIANPASSWORDADD;
    private javax.swing.JTextField ISIANUSERNAMEADD1;
    private javax.swing.JLabel PASSWORDADD;
    private javax.swing.JLabel USERNAMEADD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
